- name: Déploiement complet de Bmarket
  hosts: bmarket
  become: true
  vars:
    ghcr_username: "{{ ghcr_username }}"
    ghcr_token: "{{ ghcr_token }}"
    domain_name: "{{ domain_name }}"
    database_url: "{{ database_url }}"

  tasks:

    - name: 📦 Installer les dépendances
      apt:
        name:
          - docker.io
          - docker-compose
          - nginx
          - certbot
          - python3-certbot-nginx
          - ufw
          - fail2ban
        state: present
        update_cache: true

    - name: 🔑 Se connecter à GHCR
      shell: echo "{{ ghcr_token }}" | docker login ghcr.io -u "{{ ghcr_username }}" --password-stdin

    - name: 📦 Télécharger la dernière image Docker
      shell: docker pull ghcr.io/{{ ghcr_username }}/bmarket:latest

    - name: 🛑 Arrêter et supprimer l'ancien conteneur (si existant)
      shell: docker rm -f bmarket || true

    - name: 🚀 Démarrer le conteneur
      shell: |
        docker run -d --name bmarket \
          -p 3000:3000 \
          -e DATABASE_URL="{{ database_url }}" \
          ghcr.io/{{ ghcr_username }}/bmarket:latest

    - name: 🔄 Configurer Nginx pour Bmarket
      copy:
        dest: "/etc/nginx/sites-available/bmarket"
        content: |
          server {
              listen 80;
              server_name {{ domain_name }} www.{{ domain_name }};

              location / {
                  proxy_pass http://localhost:3000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: 🔗 Activer la configuration Nginx
      file:
        src: "/etc/nginx/sites-available/bmarket"
        dest: "/etc/nginx/sites-enabled/bmarket"
        state: link

    - name: 🧹 Supprimer la configuration par défaut
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent

    - name: 🔄 Redémarrer Nginx
      systemd:
        name: nginx
        state: restarted
        enabled: true

    - name: 🔒 Générer un certificat SSL avec Certbot
      shell: certbot --nginx -d {{ domain_name }} -d www.{{ domain_name }} --non-interactive --agree-tos -m contact@{{ domain_name }}

    - name: 🔄 Redémarrer Nginx après Certbot
      systemd:
        name: nginx
        state: restarted
