---
- name: Déploiement de Bmarket sur VPS
  hosts: bmarket
  become: true  # Exécute les commandes avec sudo
  vars:
    ghcr_username: "{{ lookup('env', 'GHCR_USERNAME') }}"
    ghcr_token: "{{ lookup('env', 'GHCR_TOKEN') }}"
  tasks:

    - name: 🏗️ Mettre à jour les paquets
      apt:
        update_cache: yes

    - name: 📦 Installer Docker et Docker Compose
      apt:
        name: ["docker.io", "docker-compose"]
        state: present

    - name: 🏗️ Vérifier si l’utilisateur deploy existe
      command: id deploy
      register: deploy_user
      ignore_errors: yes

    - name: 👤 Créer l'utilisateur deploy s'il n'existe pas
      user:
        name: deploy
        groups: docker
        shell: /bin/bash
      when: deploy_user.rc != 0

    - name: 🔑 Autoriser deploy à exécuter sudo sans mot de passe
      copy:
        dest: /etc/sudoers.d/deploy
        content: "deploy ALL=(ALL) NOPASSWD:ALL"
        mode: "0440"

    - name: 📂 S'assurer que le dossier de déploiement existe
      file:
        path: /home/deploy/bmarket
        state: directory
        owner: deploy
        group: deploy
        mode: '0755'

    - name: 📝 Générer le fichier docker-compose.yml
      copy:
        dest: /home/deploy/bmarket/docker-compose.yml
        content: |
          version: '3.9'
          services:
            app:
              image: ghcr.io/bouissai/bmarket:latest
              container_name: bmarket
              restart: always
              ports:
                - "3000:3000"
              env_file:
                - .env
        owner: deploy
        group: deploy
        mode: '0644'

    - name: 🔑 Se connecter à GHCR
      command: docker login ghcr.io -u {{ ghcr_username }} -p {{ ghcr_token }}

    - name: 📥 Récupérer la dernière image Docker
      command: docker-compose pull
      args:
        chdir: /home/deploy/bmarket

    - name: 🛑 Arrêter et supprimer l’ancien conteneur
      command: docker-compose down
      args:
        chdir: /home/deploy/bmarket
      ignore_errors: yes

    - name: 🚀 Démarrer les nouveaux conteneurs
      command: docker-compose up -d
      args:
        chdir: /home/deploy/bmarket
