- hosts: bmarket
  become: no
  tasks:

    ## 1️⃣ Vérifier et installer Docker si nécessaire
    - name: Vérifier si Docker est installé
      shell: command -v docker
      register: docker_check
      changed_when: false
      ignore_errors: true

    - name: Installer Docker et Docker Compose si manquants
      become: yes
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
      when: docker_check.rc != 0

    ## 2️⃣ Déploiement Bmarket
    - name: Vérifier si l'image Docker est à jour
      shell: docker images -q ghcr.io/bouissai/bmarket:latest
      register: docker_image
      changed_when: false
      ignore_errors: true

    - name: Récupérer la nouvelle image Docker uniquement si nécessaire
      shell: sudo docker pull ghcr.io/bouissai/bmarket:latest
      when: docker_image.stdout == ""

    - name: Vérifier si le conteneur Bmarket tourne
      shell: docker ps -q -f name=bmarket
      register: bmarket_container
      changed_when: false
      ignore_errors: true

    - name: Arrêter et supprimer l'ancien conteneur si nécessaire
      shell: sudo docker stop bmarket && sudo docker rm bmarket
      when: bmarket_container.stdout != ""

    ## 3️⃣ S'assurer que le dossier de déploiement existe
    - name: S'assurer que le dossier de déploiement existe
      file:
        path: /home/deploy/bmarket
        state: directory
        owner: deploy
        group: deploy
        mode: '0755'

    - name: Vérifier si le fichier docker-compose.yml est présent
      stat:
        path: /home/deploy/bmarket/docker-compose.yml
      register: compose_file

    - name: Copier le fichier docker-compose.yml si manquant
      copy:
        src: ./docker-compose.yml
        dest: /home/deploy/bmarket/docker-compose.yml
        owner: deploy
        group: deploy
        mode: '0644'
      when: not compose_file.stat.exists

    ## 4️⃣ Lancer l'application avec Docker Compose
    - name: Lancer Bmarket avec Docker Compose
      shell: |
        cd /home/deploy/bmarket
        sudo docker-compose pull
        sudo docker-compose up -d
