- name: Déploiement complet de Bmarket
  hosts: bmarket
  become: true
  vars:
    ghcr_username: "{{ ghcr_username }}"
    ghcr_token: "{{ ghcr_token }}"
    domain_name: "{{ domain_name }}"
    postgres_user: "{{ lookup('env', 'POSTGRES_USER') }}"
    postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
    postgres_db: "{{ lookup('env', 'POSTGRES_DB') }}"
    backup_dir: "/home/deploy/db_backups"

  tasks:

    # 📦 Installer les dépendances
    - name: 📦 Installer les paquets nécessaires
      apt:
        name:
          - docker.io
          - docker-compose
          - nginx
          - certbot
          - python3-certbot-nginx
          - ufw
          - fail2ban
          - postgresql
          - postgresql-contrib
        state: present
        update_cache: true

    # 🔄 Vérifier et démarrer PostgreSQL
    - name: 🔄 Vérifier si PostgreSQL est en cours d'exécution
      command: systemctl is-active postgresql
      register: pg_status
      changed_when: false
      ignore_errors: true

    - name: 🚀 Démarrer PostgreSQL si nécessaire
      systemd:
        name: postgresql
        state: started
        enabled: true
      when: pg_status.stdout != "active"

    # 🛢️ Configurer PostgreSQL pour les connexions externes
    - name: 🔧 Modifier pg_hba.conf pour autoriser les connexions externes
      lineinfile:
        path: /etc/postgresql/15/main/pg_hba.conf
        line: "host all all 0.0.0.0/0 md5"
        create: yes
      notify: Redémarrer PostgreSQL

    - name: 🔧 Modifier postgresql.conf pour écouter sur toutes les interfaces
      lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        regexp: "^#listen_addresses = 'localhost'"
        line: "listen_addresses = '*'"
      notify: Redémarrer PostgreSQL

    # 🛢️ Créer l'utilisateur PostgreSQL
    - name: 🛢️ Vérifier si l'utilisateur PostgreSQL existe
      become_user: postgres
      command: psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='{{ postgres_user }}'"
      register: user_exists
      changed_when: false
      ignore_errors: true

    - name: 🛢️ Créer l'utilisateur PostgreSQL si inexistant
      become_user: postgres
      postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        role_attr_flags: CREATEDB
      when: user_exists.stdout != "1"

    # 🛢️ Créer la base de données PostgreSQL
    - name: 📂 Vérifier si la base de données existe
      become_user: postgres
      command: psql -tAc "SELECT 1 FROM pg_database WHERE datname='{{ postgres_db }}'"
      register: db_exists
      changed_when: false
      ignore_errors: true

    - name: 🛢️ Créer la base de données si elle n'existe pas
      become_user: postgres
      postgresql_db:
        name: "{{ postgres_db }}"
        owner: "{{ postgres_user }}"
      when: db_exists.stdout != "1"

    # 📂 Configurer un dossier de sauvegarde
    - name: 📂 Créer un dossier pour stocker les backups
      file:
        path: "{{ backup_dir }}"
        state: directory
        owner: postgres
        group: postgres
        mode: "0700"

    # 🛢️ Sauvegarde de la base de données avant chaque déploiement
    - name: 🛢️ Sauvegarde de la base de données
      become_user: postgres
      command: pg_dump -U {{ postgres_user }} -F c -b -v -f {{ backup_dir }}/bmarket_backup_$(date +%F_%H-%M-%S).dump {{ postgres_db }}
      ignore_errors: true

    # 🔑 Se connecter à GitHub Container Registry (GHCR)
    - name: 🔑 Se connecter à GHCR
      shell: echo "{{ ghcr_token }}" | docker login ghcr.io -u "{{ ghcr_username }}" --password-stdin

    # 📦 Télécharger l'image Docker
    - name: 📦 Télécharger la dernière image Docker
      shell: docker pull ghcr.io/{{ ghcr_username }}/bmarket:latest

    # 🛑 Arrêter l'ancien conteneur
    - name: 🛑 Arrêter et supprimer l'ancien conteneur (si existant)
      shell: docker rm -f bmarket || true
    - name: 🚨 Vérification de DATABASE_URL avant le déploiement
      debug:
        msg: "DATABASE_URL = postgresql://{{ postgres_user }}:{{ postgres_password }}@127.0.0.1:5432/{{ postgres_db }}"

    # 🚀 Démarrer le conteneur avec PostgreSQL
    - name: 🚀 Démarrer le conteneur
      shell: |
        docker run -d --name bmarket \
          -p 3000:3000 \
          -e DATABASE_URL="postgresql://{{ postgres_user }}:{{ postgres_password }}@127.0.0.1:5432/{{ postgres_db }}" \
          ghcr.io/{{ ghcr_username }}/bmarket:latest


    # 🔄 Configurer Nginx comme reverse proxy
    - name: 🔄 Configurer Nginx
      copy:
        dest: "/etc/nginx/sites-available/bmarket"
        content: |
          server {
              listen 80;
              server_name {{ domain_name }} www.{{ domain_name }};

              location / {
                  proxy_pass http://localhost:3000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: 🔗 Activer la configuration Nginx
      file:
        src: "/etc/nginx/sites-available/bmarket"
        dest: "/etc/nginx/sites-enabled/bmarket"
        state: link

    - name: 🧹 Supprimer la configuration Nginx par défaut
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent

    - name: 🔄 Redémarrer Nginx
      systemd:
        name: nginx
        state: restarted
        enabled: true

    # 🔒 Générer un certificat SSL avec Let's Encrypt
    - name: 🔒 Générer un certificat SSL avec Certbot
      shell: certbot --nginx -d {{ domain_name }} -d www.{{ domain_name }} --non-interactive --agree-tos -m contact@{{ domain_name }}

    - name: 🔄 Redémarrer Nginx après Certbot
      systemd:
        name: nginx
        state: restarted

  handlers:
    - name: Redémarrer PostgreSQL
      systemd:
        name: postgresql
        state: restarted
